name: osx

on: push

jobs:
  integration_test:
    runs-on: macos-12
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Docker
        run: |
          brew install docker colima
          colima start
      - name: Run s3ninja
        run: docker run -p 9444:9000 --name=s3ninja --detach scireum/s3-ninja:8.1.1
      - name: Build & run bazels3cache
        run: |
          go build -o ./bazels3cache app/main.go
          ./bazels3cache --bucket bazel --s3url http://localhost:9444/s3
      - name: Test
        run: |
          export s3_host=localhost:9444
          export test_workspace=integration_test/workspace
          export bazels3cache=./bazels3cache
          python3 -u ./integration_test/test.py
