---
name: Release

on:
  push:
    tags: [ "*" ]

jobs:
  release:
    name: Create release
    # strategy:
    #   matrix:
    #     target:
    #       - { os: 'linux', arch: 'amd64' }
    #       - { os: 'linux', arch: 'arm64' }
    #       - { os: 'darwin', arch: 'amd64' }
    #       - { os: 'darwin', arch: 'arm64' }
    #       - { os: 'windows', arch: 'amd64' }
    runs-on: ubuntu-22.04
    steps:
      - name: Set up toolchain
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.1
        id: go

      - name: Check out code
        uses: actions/checkout@v3

      - name: Build binary
        run: go build -o bazels3cache ./...

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: bazels3cache
          path: bazels3cache
