name: tests

on: [push]

jobs:
  Run integration test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          docker-compose -f docker-compose.test.yaml up --build --force-recreate --exit-code-from integration
