name: ubuntu

on: push

jobs:
  integration_test:
    name: Run integration test
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run integration test
        run: |
          make run-integration-test

  build_release:
    name: Build release binary
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run integration test
        run: |
          make build
